# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_relation',
            field=models.CharField(default='Father', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='Parent', max_length=30),
            preserve_default=False,
        ),
    ]
