# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='static/safety_image/')),
            ],
        ),
    ]
